### ISSUE TITLE
Intermittent results

### ISSUE THREAD

**Issue by christopherkeller** [jeffgreenca/codesort#2]
Neat implementation, but I've had some mixed results running across a couple of our repos. On some of them, it works flawlessly, on others I get the following message consistently.

```$ docker run -v `pwd`/groves:/repo:ro jeffgreenca/codesort```

```
Traceback (most recent call last):
  File "codesort.py", line 90, in <module>
    main(args.repo, count=args.num_results, limit=args.commits, bare=args.bare, single=args.single, export=args.export)
  File "codesort.py", line 64, in main
    bb = multi.betweenness_centrality_parallel(graph, weight='distance')
  File "/app/multi.py", line 39, in betweenness_centrality_parallel
    bt_c = bt_sc[0]
IndexError: list index out of range
```

**Comment by jeffg-dev** [comment]
Can you try on the failing repos with the `-s` switch to disable the multiprocessing centrality calculation, and report the results?

**Comment by christopherkeller** [comment]
I think might be an issue with the default assumptions.

This works fine:

```$ docker run -v `pwd`/core:/repo:ro jeffgreenca/codesort -s /repo```

Removing the `-s` flag and passing the mount point also works fine (and produces the same results):

```$ docker run -v `pwd`/core:/repo:ro jeffgreenca/codesort /repo```

**Comment by jeffg-dev** [comment]
Oh, whoops, I made a breaking change to argument names and didn't update the Dockerfile default arguments.

**Comment by christopherkeller** [comment]
Confirmed, updated the docker image and zero issues, thanks.
