### ISSUE TITLE
Add avoiding rules for specific patterns

### ISSUE THREAD

**Issue by ipesanz** [jeffgreenca/codesort#6]
Hi,

I was testing the project with one of my repos and it also considers the output files stored in the repo.  (.idea/, .out , .gitignore, etc.)

Would be possible to add an argument and restrict some kind of files by pattern?
I was thinking on: 
* Paths to avoid like /out/production... 
* And hidden files like .idea or .gitignore

Or well.... just focus on the files of one specific path like /src/...

**Comment by jeffg-dev** [comment]
I think adding `--exclude` and `--include` arguments that allow glob patterns would satisfy this.

At the same time, the tool only considers files stored in source control, so if you are building artifacts and storing them in source control for each commit, arguably that's an important characteristic of the repository and would want this tool to it call out.
